### PR TITLE
Use new registerQuickActions() method to insert docs menubar entry

### PR DESCRIPTION
**Pull request by mjauvin**
Before:
Screenshot from 2021-01-26 09-33-23
Screenshot from 2021-01-26 09-33-58

After:
Screenshot from 2021-01-26 09-35-09
Screenshot from 2021-01-26 09-35-25

### CODE REVIEW

**Comment by LukeTowers** [comment]
You'll also need to remove the combiner bundle registration in plugin.php and the addCss call

**Comment by bennothommo** [comment]
@mjauvin instead of changing the class, you could use the new [quick actions](https://github.com/octobercms/october/pull/5344) functionality in 1.1.1 to insert the link. Then you wouldn't need that horrible `linkInserter.js` any longer. :)

**Comment by mjauvin** [comment]
Very nice addition @bennothommo !

**Comment by mjauvin** [comment]
@bennothommo would it be a lot of work to add the Events documentation in here?

ref. https://octobercms.com/docs/api/backend/ajax/beforerunhandler

**Comment by bennothommo** [comment]
@mjauvin I was leaving it undocumented for now until we have a way of collapsing the quick actions if people go overboard with them.

**Comment by mjauvin** [comment]
What do you mean @bennothommo?

**Comment by LukeTowers** [comment]
@mjauvin we don't want lots of people using that functionality because it would be bad for UX with a lot of quick actions registered unless we had some way of allowing the user to control that better.

**Comment by bennothommo** [comment]
@LukeTowers I misread @mjauvin's initial comment - he means making the Event docs available in the Docs plugin. You've already got an issue posted for that, I believe.

**Comment by LukeTowers** [comment]
@bennothommo I also misread it 😂

**Comment by bennothommo** [comment]
Here it is: https://github.com/rainlab/docs-plugin/issues/3

**Pull request merged**
